### ISSUE TITLE
remove with statements

### ISSUE THREAD

**Issue by aresn** [aadsm/jschardet#11]
Currently jschardet can not be used under JavaScript strict mode because of **with** statement in following files : 
escsm.js
mbcssm.js. 

also line 372 in mbcssm.js should be "**jschardet.UCS2BE_cls**" instead of "UCS2BE_cls"

**Comment by aadsm** [comment]
Any chance I'll get a PR with this fix? :-)

**Comment by aadsm** [comment]
Fixed with https://github.com/aadsm/jschardet/pull/16
