### ISSUE TITLE
UTF-8 or utf-8, we need to make a decision~

### ISSUE THREAD

**Issue by LeoYuan** [aadsm/jschardet#12]
mostly, if a file was detected as utf-8, the lower case of `utf-8` returned~
BUT, if a file was detected with confidence of 1, then the upper case of `UTF-8` returned~

I don't think this is a good choice to return two kinds of `utf-8`, could you unify them?

**Comment by aadsm** [comment]
Good catch, let's go with `UTF-{8,16}` can you provide a PR please? :)

**Comment by LeoYuan** [comment]
I'm glad to, but in my country(China), it's hard to push stuffs to Github without vpn, so how about I just point out several occurences of the lower `utf-8`, and then you correct them?
```
// file README.md
line 23: 
{ encoding: "utf-8", confidence: 0.9690625 }   

// src/utf8prober.js
line 50: 
return "utf-8";

// tests/jschardet.js
line 28: 
equals( jschardet.detect(str).encoding, "utf-8" );
```

**Comment by aadsm** [comment]
Oh I see. Thank you for pointing out the places.
