### ISSUE TITLE
Usage instructions in browser

### ISSUE THREAD

**Issue by treyhunner** [aadsm/jschardet#22]
I didn't see any instructions for using this library with a file read from the browser.

I tried using the [File API](https://www.w3.org/TR/FileAPI/) to read a file as text and then detect the encoding. The guessed encoding always seems to be either ascii or windows-1251. I suspect that when reading the file as text it is automatically decoded when reading using the File API (I'm not familiar enough with unicode in the browser to be sure).

I noticed that the tests all use hard-coded strings instead of files. Is there a recommended method for using this library with files in the browser? Thanks! :smile:

**Comment by aadsm** [comment]
Can you show me how are you trying to read the file?

**Comment by sir-script** [comment]
It happens to me too.
I've been working on a CSV-Import Tool. 
As soon as the user uploads a CSV File, my script gets the raw data and calls jschardet.detect to find out the right charset encoding. The PapaParse Library ( CSV Parser) now uses this information to convert the raw CSV data and transform the data into the right charset format.
I**t works very well for CSV Files with the encoding types Iso 8859-1, windows 1252, iso 8859-2...**
**But not for CSV Files with utf-8 encoding**: 
jschardet detects always windows 1252 (wrong).

CSV File with utf-8:
[Newsletter_Export_header_utf8.csv.zip](https://github.com/aadsm/jschardet/files/439366/Newsletter_Export_header_utf8.csv.zip)


Screenshot of my Code:
![image](https://cloud.githubusercontent.com/assets/2495836/18006800/c0041eb4-6ba1-11e6-8901-da05eaa75325.png)

More generic example for the File Reader Api:
[http://www.htmlgoodies.com/beyond/javascript/read-text-files-using-the-javascript-filereader.html#fbid=49U42gmOPhW]

**Comment by sir-script** [comment]
I forgot something: This happens also with larger CSV Files ( 100 entries ) ...

**Comment by aadsm** [comment]
@treyhunner yeah, the problem is exactly what you point out, `readAsText` reads the file contents as UTF-8 when no encoding is specified.

You need to convert it to a string using array buffers, it's not ideal but it's the same strategy used for node Buffers: https://jsfiddle.net/vbogvqa8/.

This should probably be added to the library itself.

**Comment by sir-script** [comment]
@aadsm Thank you Alfonso, it was exactly that problem you have mentioned. And your solution works great 👍

**Comment by kurtpetrek** [comment]
Hello, sorry but when I run npm install and get the latest version of jschardet (2.1.1) and copy the example from the js fiddle and select a csv document I get windows 1252, which is incorrect. The same csv file will read SHIFT_JIS when using the js fiddle, which is correct.  If I npm install jschardet @1.4.1, which appears to be the version the js fiddle loads, the csv will be detected as SHIFT_JIS.  I'm not sure if I should install and use this older version or if there is another way in the current version I can check the encoding format of a document in the browser.

**Comment by FireController1847** [comment]
Howdy. I am in agreement with the above, except in my case it seems that many files (including regular UTF-8 ones) are coming up as ASCII using the JSFiddle provided. I'm not sure why this would be the case, but I've attached each of my test files below
[This is a test file written in UTF-8.txt](https://github.com/aadsm/jschardet/files/9225533/This.is.a.test.file.written.in.UTF-8.txt)
[This is a test file written in UTF-8 with BOM.txt](https://github.com/aadsm/jschardet/files/9225534/This.is.a.test.file.written.in.UTF-8.with.BOM.txt)
[This is a test file written in UTF-16 LE.txt](https://github.com/aadsm/jschardet/files/9225535/This.is.a.test.file.written.in.UTF-16.LE.txt)
[This is a test file written in Windows 1252.txt](https://github.com/aadsm/jschardet/files/9225536/This.is.a.test.file.written.in.Windows.1252.txt)
[This is a test file written in ASCII.txt](https://github.com/aadsm/jschardet/files/9225537/This.is.a.test.file.written.in.ASCII.txt)
.
