### ISSUE TITLE
Error in UTF-8 with spanish characters

### ISSUE THREAD

**Issue by dabroder** [aadsm/jschardet#23]
Detects "Diseño de aplicación" how 'GB2312' encoding

**Comment by aadsm** [comment]
Small pieces of text are hard to detect. Encoding detection is not deterministic (for most cases) and relies on heuristic methods.
If you write "Diseño de aplicación" three times then the detector is able to find UTF-8.

`jschardet.detect` returns the encoding with the best confidence but you can set `jschardet.Constants._debug = true;` to see the confidence of all other encodings.
In this case UTF-8 is 0.7525 which is the second best next to GB2312 0.99.

I hope this helps.
