### ISSUE TITLE
Distinct macintosh from ISO-8859-2?

### ISSUE THREAD

**Issue by Lcfvs** [aadsm/jschardet#32]
Hi,

When I try to detect the encoding of a text (macintosh) file content, your tool returns ISO-8859-2.

Then I try to decode, it doesn't works with that tool : https://github.com/mathiasbynens/iso-8859-2 

But it works with this one : https://github.com/mathiasbynens/macintosh

Is there a way to distinct them, please?

**Comment by aadsm** [comment]
This library is a port of the python's chardet and I've noticed they have disabled the`ISO-8859-2` detection until they retrain the model used, so at this time `ISO-8859-2` can't be faulty in the confidence it yields.
Can you also check what are the other encodings guessed by setting `jschardet.Constants._debug = true;`.

**Comment by Lcfvs** [comment]
Ok, ok, thanks :)
