### ISSUE TITLE
Clarify License

### ISSUE THREAD

**Issue by bpasero** [aadsm/jschardet#33]
Can you include a LICENSE file in this repository, similar to the one in https://github.com/chardet/chardet/blob/master/LICENSE

**Comment by aadsm** [comment]
Sure, added it here https://github.com/aadsm/jschardet/commit/b8fe56d1d2f77ac53326a915c8e1f837d6fcfe2e.
The license was mentioned in https://github.com/aadsm/jschardet/blob/master/package.json#L7

**Comment by bpasero** [comment]
@aadsm thanks so much!
