### ISSUE TITLE
Cannot use jschardet from browser using  jschardet.min.js

### ISSUE THREAD

**Issue by alichur** [aadsm/jschardet#36]
Hello, thanks for jschardet!

The readme instructions for browser usage suggest including `jschardet.min.js` in the webpage. This does not work as the file contains Node.js filesystem functions that fail, for example `readFileSync`.

Note that the cdnjs option for browser usage does not use Node.js and runs successfully.

**Comment by aadsm** [comment]
I've just published a new version where this problem should be fixed. Thanks for the report.
