### ISSUE TITLE
Can I get the list of encoding in confidence order?

### ISSUE THREAD

**Issue by hotohoto** [aadsm/jschardet#40]
I want to suggest users the encoding list letting them pick one.

**Comment by aadsm** [comment]
At this point there’s no way to get this in a usable form. There’s only debug output to stdout that will tell you this if you set `jschardet.Constants._debug = true`. You can find this here: https://github.com/aadsm/jschardet/blob/62986ff68c305281cbd8a75c6764e7477400fd85/src/sbcharsetprober.js.
I think it would be great to have an option that returns this data though.
