### ISSUE TITLE
Performance regression in 2.*

### ISSUE THREAD

**Issue by ziggi** [aadsm/jschardet#53]
In VS Code 1.41 jschardet was updated from 1.6.0 to 2.1.1, it introduced some performance problems.

Check this for more information (screens and cpuprofile):
https://github.com/microsoft/vscode/issues/87205

**Comment by aadsm** [comment]
@ziggi This is unexpected as there hasn't been any logical changes to the library, just some NFC refactoring. There are only like 10 commits between those 2 versions, could you bisect them to find the offending commit?

**Comment by bpasero** [comment]
@ziggi can you share the file that is causing the performance problem? I just tried to reproduce with a 200kb file (all ASCII though) and it detected in 14ms without performance overhead. I am using this code with latest `jschardet`:

```js
var jschardet = require("jschardet");
var fs = require("fs");

const buf = fs.readFileSync('large.js');

const now = Date.now();
jschardet.detect(buf);

console.log(Date.now() - now);
```

**Comment by ziggi** [comment]
The problem is definitely not in the `jschardet`. I just tried to reproduce it on test repo and I saw what the freezes appears only if opened file is tracked by a git.

Steps to reproduce:

- Clone the [repo](https://github.com/ziggi/vscode_test_repo): `git clone https://github.com/ziggi/vscode_test_repo.git`
- Open folder with vscode 1.41 or 1.42
- Open `test_file.txt` file and scroll it, you will see freezes
- After it you can switch tab to another and switch back, you will see freezes again
- Then you can copy the file and open it, you will not see any freezes

**Comment by bpasero** [comment]
@ziggi @aadsm I can reproduce a slow encoding guess with both `1.6.x` and `2.x` versions of `jschardet`. Steps:
* `git clone https://github.com/bpasero/jschardet-perf.git`
* `yarn`
* `node index.js`

Perf profile: 

[CPU-20200105T085702.cpuprofile.zip](https://github.com/aadsm/jschardet/files/4022987/CPU-20200105T085702.cpuprofile.zip)

**Comment by ziggi** [comment]
@bpasero I think it's just a big file. Anyway, no freezes in vscode 1.40.
