### ISSUE TITLE
Regression in V2: EUC-KR string ("ÇÑ±¹¾î") is incorrectly detected as 'windows-1252'; works in V1-4-1.

### ISSUE THREAD

**Issue by thomas5280** [aadsm/jschardet#61]
Hi everyone, I hope you are well and thank you for this excellent work. We are looking at using this project to auto-correct filenames in archives (e.g., TAR) that do not support unicode.

Here's what should be a very simple real-world example. The issue repros for me in 2-1-1 and 2-2-1

**TEST STRING:** 
ÇÑ±¹¾î.txt

**EXPECTED (V1-4-1 output):** 
{ encoding: "EUC-KR", confidence: 0.99 }

**ACTUAL:**
{ encoding: "windows-1252", confidence: 0.95 }

**MORE INFO:**
Works as expected in 1-4-1, for example, in the demo fiddle:
https://jsfiddle.net/vbogvqa8/

Issue repros even when removing the '.txt' extension.

I tried all the many different ways Including:
jschardet.detect('\xc7\xd1\xb1\xb9\xbe\xee\x2e')

I was sure to very carefully check the input values to the detection string:

adding 199, Ç
adding 209, Ñ
adding 177, ±
adding 185, ¹
adding 190, ¾
adding 238, î
adding 46, .
adding 116, t
adding 120, x
adding 116, t

The debug log indicates early failure of EUC-KR confidence = 0.01, I'm wondering if we're hitting some hard-coded heuristic there (maybe minimum string length or something?).

**DEBUG LOG**

SHIFT_JIS prober hit error at byte 5

jschardet2-2-1.min.js:631 EUC-TW prober hit error at byte 2

jschardet2-2-1.min.js:155 UTF-8 not active

jschardet2-2-1.min.js:155 SHIFT_JIS not active

jschardet2-2-1.min.js:155 EUC-JP confidence = 0.01

jschardet2-2-1.min.js:155 GB2312 confidence = 0.01

jschardet2-2-1.min.js:155 EUC-KR confidence = 0.01

jschardet2-2-1.min.js:155 Big5 confidence = 0.01

jschardet2-2-1.min.js:155 EUC-TW not active

jschardet2-2-1.min.js:155 UTF-8 not active

jschardet2-2-1.min.js:155 SHIFT_JIS not active

jschardet2-2-1.min.js:155 EUC-JP confidence = 0.01

jschardet2-2-1.min.js:155 GB2312 confidence = 0.01

jschardet2-2-1.min.js:155 EUC-KR confidence = 0.01

jschardet2-2-1.min.js:155 Big5 confidence = 0.01

jschardet2-2-1.min.js:155 EUC-TW not active

jschardet2-2-1.min.js:661 EUC-JP confidence 0.01
jschardet2-2-1.min.js:155 windows-1251 confidence = 0

jschardet2-2-1.min.js:155 KOI8-R confidence = 0

jschardet2-2-1.min.js:155 ISO-8859-5 confidence = 0

jschardet2-2-1.min.js:155 MacCyrillic confidence = 0.01

jschardet2-2-1.min.js:155 IBM866 confidence = 0.01

jschardet2-2-1.min.js:155 IBM855 confidence = 0

jschardet2-2-1.min.js:155 ISO-8859-7 confidence = 0

jschardet2-2-1.min.js:155 windows-1253 confidence = 0

jschardet2-2-1.min.js:155 ISO-8859-5 confidence = 0

jschardet2-2-1.min.js:155 windows-1251 confidence = 0

jschardet2-2-1.min.js:155 ISO-8859-2 confidence = 0

jschardet2-2-1.min.js:155 windows-1250 confidence = 0

jschardet2-2-1.min.js:155 TIS-620 confidence = 0.22488825752260216

jschardet2-2-1.min.js:155 ISO-8859-8 confidence = 0

jschardet2-2-1.min.js:155 ISO-8859-8 confidence = 0

jschardet2-2-1.min.js:155 ISO-8859-8 confidence = 0

jschardet2-2-1.min.js:155 windows-1251 confidence = 0

jschardet2-2-1.min.js:155 KOI8-R confidence = 0

jschardet2-2-1.min.js:155 ISO-8859-5 confidence = 0

jschardet2-2-1.min.js:155 MacCyrillic confidence = 0.01

jschardet2-2-1.min.js:155 IBM866 confidence = 0.01

jschardet2-2-1.min.js:155 IBM855 confidence = 0

jschardet2-2-1.min.js:155 ISO-8859-7 confidence = 0

jschardet2-2-1.min.js:155 windows-1253 confidence = 0

jschardet2-2-1.min.js:155 ISO-8859-5 confidence = 0

jschardet2-2-1.min.js:155 windows-1251 confidence = 0

jschardet2-2-1.min.js:155 ISO-8859-2 confidence = 0

jschardet2-2-1.min.js:155 windows-1250 confidence = 0

jschardet2-2-1.min.js:155 TIS-620 confidence = 0.22488825752260216

jschardet2-2-1.min.js:155 ISO-8859-8 confidence = 0

jschardet2-2-1.min.js:155 ISO-8859-8 confidence = 0

jschardet2-2-1.min.js:155 ISO-8859-8 confidence = 0

jschardet2-2-1.min.js:661 TIS-620 confidence 0.22488825752260216
jschardet2-2-1.min.js:661 windows-1252 confidence 0.95

**Comment by aadsm** [comment]
For some reason I stopped getting updates from github so I only saw this now, will check it on weekend.

**Comment by thomas5280** [comment]
Hi there! I wanted to see if you were able to reproduce this? The interesting thing is that it works in v1.4, so it seems to be an actual regression.

Anything I can do to help? It seems like it might be more of a logic bug than a statistics bug.

I think this command will reproduce the issue:

`jschardet.detect('\xc7\xd1\xb1\xb9\xbe\xee\x2e')`

**Comment by aadsm** [comment]
This was the commit that introduced the change you see: https://github.com/aadsm/jschardet/commit/5288bcee2214a8d347afa0397462d71ce86e8811

Unfortunately, this change was made because it was overfit bug that the python version of chardet also fixed here: https://github.com/chardet/chardet/commit/c0f1ab5889abc719886c420ad3f291a8b6bdee3b
bugtrack here:  https://bugzilla.mozilla.org/show_bug.cgi?id=306272

Because of this I'm not going to change it :(. Sorry about that but encoding detection will always be based on probability heuristics, and it's especially hard for really small sequences of bytes like the example you give.
