### ISSUE TITLE
big5 incorrectly detected as windows-1252

### ISSUE THREAD

**Issue by chenxiaoba** [aadsm/jschardet#62]
It's correct in your big5 test case "次常用國字標準字體表",
but if i use "你好" in big5 encoded( str = "\xA7\x41\xA6\x6E"), it was detected to { encoding: 'windows-1252', confidence: 0.95 }

**Comment by aadsm** [comment]
Big5 is detected through character frequency and since "你好" is only 2 characters it's going to be really hard to detect the right one :(. I've just added a `detectAll`, maybe you can use it to see all the encodings that are detected, I wonder if the second one is the Big5.

**Comment by chenxiaoba** [comment]
Thank you! I tried it, the second one is not Big5. But as you said, It's hard to detect only two word. 
```
[ 
  {encoding: "windows-1252", confidence: 0.95},
  {encoding: "SHIFT_JIS", confidence: 0.01},
  {encoding: "windows-1251", confidence: 0.01}
]
```

**Comment by aadsm** [comment]
It is not 😬. It is incredibly hard to correctly detect based on very few characters because the detection is made by a probabilistic heuristic.
