### ISSUE TITLE
return all encoding and confidences

### ISSUE THREAD

**Issue by janbrchan** [aadsm/jschardet#63]
It will be possible to return all of encodings and confidences? We need this in VSCODE
https://github.com/microsoft/vscode/issues/36951#issuecomment-721142005

**Comment by aadsm** [comment]
For some reason I stopped getting updates from github so I only saw this now, will check it on weekend.

**Comment by aadsm** [comment]
I've implemented that and also published a new version 2.3.0 with it. I didn't do thorough testing so if something is missing please ping me.
