### ISSUE TITLE
TextDecoder label incompatibility: 'ibm855' and 'maccyrillic' (should be x-mac-cyrillic?)

### ISSUE THREAD

**Issue by thomas5280** [aadsm/jschardet#65]
I've found two instances where the encoding string output by jschardet doesn't conform to what I think is effectively the defacto standard, in Web-browser based TextDecoder/TextEncoder:

TextDecoder Docs:
https://developer.mozilla.org/en-US/docs/Web/API/TextDecoder/TextDecoder

This is the standard list of encodings and aliases:
https://developer.mozilla.org/en-US/docs/Web/API/Encoding_API/Encodings

And:
https://developer.mozilla.org/en-US/docs/Web/API/TextDecoder/encoding

Official Spec:
https://encoding.spec.whatwg.org/#dom-textdecoder-encoding

jschardet outputs 'maccyrillic', but seems likely this is better called 'x-mac-cyrillic' which is officially documented here:
https://en.wikipedia.org/wiki/Mac_OS_Cyrillic_encoding

'x-mac-cyrillic' is the correct one per the TextDecoder standard.

Another tricky one is ibm855:
https://en.wikipedia.org/wiki/Code_page_855

This has no equivalent in TextDecoder, but this is noted as being in the ISO 8859 group, perhaps ISO-8859-2 (?).

Options:
1. Change maccyrillic -> x-mac-cyrillic, its standard name
2. Do nothing, have end users translate
3. Lobby for maccyrillic to be an alias for x-mac-cyrillic (requires changes to every browser)

Recommend (1) and further discussion on recommended standard ISO mapping for ibm855.

**Comment by aadsm** [comment]
Thanks for the warning! I love the 3) option 😂. Will update.
