### ISSUE TITLE
UTF8 isn't recognized correctly

### ISSUE THREAD

**Issue by infusion** [aadsm/jschardet#8]
Hi,

I'd like to use jschardet for exactly what the original chardet was build for: parsing feeds.

But unfortunately, the parsing fails on german letters, encoded in UTF8:

var L=new Buffer([0xc3,0xa4]).toString("utf8");
console.log(jschardet.detect(L));

gives { encoding: 'windows-1252', confidence: 0.95 }

But 0xc3a4 is "ä" in utf8.

Thanks Robert

**Comment by aadsm** [comment]
You can see the list of confidences by setting `jschardet.Constants._debug = true;`.

**Comment by Ajido** [comment]
Error occurs when the debug option is enabled.

```
ReferenceError: log is not defined
    src/charsetgroupprober.js
    src/eucjpprober.js
    src/mbcharsetprober.js
    src/sbcharsetprober.js
    src/sjisprober.js
```

**Comment by aadsm** [comment]
@Ajido Thanks for the bug report, I've just fixed it and released a new version to npm.
